### ISSUE TITLE
TextureFX issue collection

### ISSUE THREAD

**Issue by joreg** [vvvv/VL.StandardLibs#175]
General
- [ ] vvvv/VL.StandardLibs#125
- [x] vvvv/VL.StandardLibs#145
- [x] vvvv/VL.StandardLibs#146
- [x] Should the fader for Mix() be a float4?
- [x] Pin order has changed, see Keying help patch
- [x] make sure default sampler is Linear, AddressUVW=wrap. and then remove node: AssignDefaultSampler
- [x] vvvv/VL.StandardLibs#529
- [x] Custom Texture input doesn't work? See Halo (Gradient)
- [x] add GenerateMipmaps attribute vvvv/VL.StandardLibs#377 
- [x] For sources with Renderformat set to Unorm subsequent filters fail
- [x] Placing any filter in the patch results in a runtime error: Attempted to divide by zero
- [x] Sort out InTex() vs. Sample() see https://github.com/vvvv/VL.StandardLibs/issues/279
- [x] missing ToGamma in pipeline
- [x] export doesn't seem to find texturefx nodes 
- [x] Control input for Filters and Mixers for per-pixel modulation
- [x] make "TextureSource" attribute @tebjan 
- [x] create Tunnels node: Rightclicking type enum pin -> throws exception @tebjan 
- [x] Base shader change doesn't trigger node recompile

Nodes
- [x] ChangeFormat needs an sRGB path
- [x] DirectionalBlur has custom control texture
- [x] Implement conversion details as discussed in https://github.com/vvvv/VL.Stride/pull/395
- [x] Move gimmick nodes to external package? Currently slows down startup and parsing a lot. see also vvvv/VL.StandardLibs#180
- [x] no good standard Blur node yet, only BoxBlur and obscure ones, activate strides gaussian blur
- [x] Don't use dynamic loops in blur shader code, use dynamic defines or different implementations
- [x] Format of sources should be sRGB?!
- [x] Replace Blend with stride binary operator
- [x] Should keying inherit from FilterBase?
