### ISSUE TITLE
Missing / Todos

### ISSUE THREAD

**Issue by antongit** [vvvv/VL.StandardLibs#49]
@azeno

- [x] ~~Windows Manipulation
   Like: SetNextWindowPos, SetNextWindowSize, SetNextWindowCollapsed...
   See: https://github.com/ocornut/imgui/blob/873e9d35acb4d629a5ba06a312201edff8b9d0f6/imgui.h#L353
   We've decided these setter nodes will be below the window.~~
   
   Addressed in vvvv/VL.StandardLibs#40
   
- [ ] Image, ImageButton
   See: https://github.com/ocornut/imgui/blob/873e9d35acb4d629a5ba06a312201edff8b9d0f6/imgui.h#L497

@antongit 

- [x] Save/Load init Settings (hopefully, state of the ui)
   https://github.com/ocornut/imgui/blob/873e9d35acb4d629a5ba06a312201edff8b9d0f6/imgui.h#L913
   See an extra issue: vvvv/VL.StandardLibs#45.
- [x] Check if joining SetResizeGripStyle and SetTitleStyle into SetWindowStyle is possible. **Joined.**
- [x] Treenode - handle IsOpen / IsVisible the same way as CollapsingHeader, but TreeNode doesn't have the `Close` button. Waits for vvvv/VL.StandardLibs#46.
- [x] Tabs - same as CollapsingHeader. Waits for vvvv/VL.StandardLibs#46.
- [x] Queries.  See: vvvv/VL.StandardLibs#39 
- [x] Commands. See: vvvv/VL.StandardLibs#40 
- [ ] Clipping
- [ ] Drag&Drop (1st: inside of the app, 2nd: from/to OS)
- [x] DragSliders
- [ ] StyleSetters: add Widgets (that are affected by this setter) into the `Tags`.
